server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://my-release-postgresql.default.svc.cluster.local:5432/postgres
    username: ${DB_USER}
    password: ${DB_PASS}
  flyway:
    enabled: true
    schemas: otus