server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://my-release-postgresql.default.svc.cluster.local:5432/postgres
    username: postgres
    password: ewoMvDsTYl
  flyway:
    enabled: true
    schemas: otus